[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "fake-useragent>=1.5.1",
    "pandas>=2.2.3",
    "schedule>=1.2.2",
    "selenium>=4.26.1",
]
